BUG indented magics aren't supported
nbQA-dev/nbQA pull request #234
Opened 2020-09-12 14:35 UTC by MarcoGorelli

closes #233

2020-09-13 07:09 UTC, girip11 commented
I will review the changes

2020-09-16 12:41 UTC, girip11 requested changes

2020-09-18 08:07 UTC, MarcoGorelli commented on nbqa/save_source.py
>      bash_cell = source and any(source[0].startswith(i) for i in ("%%script", "%%bash"))
I didn't know that worked, thanks for noticing @girip11 ! Have updated

2020-09-18 12:23 UTC, girip11 approved these changes

2020-09-18 16:28 UTC, merged