CONFIG, BREAKING Use setup.cfg instead of .nbqa.ini
nbQA-dev/nbQA pull request #236
Opened 2020-09-13 13:53 UTC by MarcoGorelli

closes #211

2020-09-13 15:08 UTC, s-weigand commented
I think the approach with `[nbqa.config]`, makes it more obvious that this is a `nbQA` only setting, so users will be less tempted to duplicate their tool configuration in there.
And it would also couple it more tightly with the CLI flag name.

Also, refactoring out some code from `_get_configs` so `config_file` and `config_prefix`, can be used as arguments would allow to easily extend it to `project.toml` support and we could keep the `.nbqa.ini` for now, throwing a `DeprecationWarning`, instead of breaking it.

2020-09-13 16:41 UTC, girip11 commented
I have not looked at the changes yet. Since nbqa is going to support **setup.cfg** for configuration instead of its own **nbqa.ini**, I suggest removing the **addopts** from the configuration. Let the users configure the tool's configuration either in `pyproject.toml` or `setup.cfg` separately from nbqa's configuration.

2020-09-14 16:57 UTC, MarcoGorelli commented
I was looking into how pydocstyle do it, and they support many different config files, for which they give an order of preference. So, they check one for a [pydocstyle] section, and if they find it, they don't check the rest. https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/config.py

Seems quite simple, so perhaps it's OK to support all 3. I would suggest:

1. PR to "officially" support setup.cfg and tox.ini (adding this one is no extra effort if we do it like pydocstyle do it), though silently keep supporting .nbqa.ini
2. Another PR to add support for pyproject.toml with `toml` as an optional dependency (I'd imagine parsing toml is a bit different, so this may take a little more work?)

2020-09-15 06:37 UTC, MarcoGorelli commented
> I suggest removing the **addopts** from the configuration. Let the users configure the tool's configuration either in `pyproject.toml` or `setup.cfg` separately from nbqa's configuration.

True, depends if there are tools which have arguments which can only be passed from the cli

2020-09-15 06:50 UTC, s-weigand commented
IMHO I would keep the addops, since users might want to have a different config for Notebooks than normal *.py files.
I.e. it is very common to a variable or function call as last line in a cell for showing the value. But liners will tell you that the statement has no effect. While this is fine in Notebooks, in *.py files this would be a Codes smell.

2020-09-15 09:29 UTC, girip11 commented
> True, depends if there are tools which have arguments which can only be passed from the cli
Agreed. But I am not sure if tools support CLI only argument.

> it is very common to a variable or function call as last line in a cell for showing the value.
Regarding this, using a statement like `print`, or `display` since **"Explicit is better than implicit"**
. Also when you add new line in the same cell, your intention of printing it has to be taken care by some other contributor or your future self. Though its a common behavior if its a smell, I feel it should be fixed.

@s-weigand I can understand your **intentions** here (maintaining a separate configuration for notebooks).  I see the python code in a jupyter notebook the same way as a python source code in terms of good practices. This makes it simple to start with.

In this case I would take the approach of the requirement coming from a user(in near future) rather than speculating the future if we don't have any compelling points now. This way we will have a broader view of the issue because we know how the users wanted the feature.

2020-09-15 09:32 UTC, girip11 commented
Let's say we proceed with two places to define flake8's configuration. 
1. pyproject.toml under flake8 section
2.  setup.cfg under nbqa addopts.

Now we are getting in to the business of dealing with multiple configurations for the same tool. You might have to merge the configurations from both places and then feed it to flake8.

2020-09-15 09:44 UTC, girip11 commented
Also if the developers need some exemption of a linting rule for a particular notebook, they should be encouraged to use a disable comment locally in the notebook (ex: `#noqa`) rather than nbqa tool trying the take care of these **disables**.

These are the reasons why I am up for removing this addopts argument. I am fine with however the way your proceed.

2020-09-15 12:09 UTC, MarcoGorelli commented
@girip11 thanks for sharing your thoughts very clearly :+1: ! From I've understood, your argument is: we should disable addopts because it allows users to have different configurations for notebooks than for python files, and that would be a bad practice. You also share concerns about it being complex to implement due to conflicts.

First, disabling addopts doesn't disallow having different configurations: you can still pass your own config file, e.g. by having this in setup.cfg:
```cfg
[nbqa.config]
flake8 = .my_flake8_config_file
```

Second, are you sure it's necessarily a bad practice? E.g. if running isort, it seems legitimate to want imports to not be sorted between cells for notebooks (e.g. with the `--treat-comment-as-code`flag) but not to want that for Python files.

Third, regarding conflicts: these are handled by the third-party tool itself. For example, if you run have setup.cfg like
```
[nbqa.config]
flake8 = .flake8
addopts = -q
```
, then nbqa will copy your `.flake8` file over to your temporary directory and then run
```
flake8 <python file> -q
```
. So what happens if you also have `-v` in `.flake8`, or something incompatible with it? Well, I don't know, but we can let flake8 deal with that, just like it normally would when it runs against Python files.

So, IMO it's OK to keep supporting it. If you disagree or if I've misrepresented your position, please do let me know!

2020-09-15 13:06 UTC, girip11 commented
@MarcoGorelli: You have captured my points clearly. I am agreeing with both of you to continue to support the addopts.

2020-09-15 13:51 UTC, girip11 requested changes

2020-09-15 13:51 UTC, girip11 commented on nbqa/__main__.py
> +                return config_file, config, "nbqa."
Could we use some CONSTANT for storing the prefix"nbqa."

2020-09-15 13:51 UTC, girip11 commented on nbqa/__main__.py
> +        return ".nbqa.ini", config, ""
Could we refactor to use a CONSTANT like `DEFAULT_CONFIG_FILE = ".nbqa.ini"`

2020-09-15 13:51 UTC, girip11 commented on nbqa/__main__.py
> +    for config_file in config_files:
We could use CONFIG_FILES directly in the for loop instead of `config_files = CONFIG_FILES`

2020-09-15 13:51 UTC, girip11 commented on nbqa/__main__.py
> +    if config_file != ".nbqa.ini":
Querying from different configurations `nbqa.ini`, `setup.cfg`, `pyproject.toml` seems to be a good place to apply polymorphism, Different configuration handlers exposing same interface to query the config. We can avoid these if/else structures. @MarcoGorelli Your thoughts on this? Do you have some sort of preference in using classes?

2020-09-15 13:51 UTC, girip11 commented on tests/conftest.py
> +    temp_file = Path(tmpdir) / "setup.cfg"
You could reuse `filename` in the definition of `temp_file`.

2020-09-15 16:39 UTC, MarcoGorelli commented
Thanks @girip11  for your (as always) excellent comments, and for holding me accountable to not writing lazy code :+1: 

Regarding polymorphism - IMO at the moment it's not too complex that we would _need_ it, but if you wanted to submit a PR for that it would be welcome!

2020-09-15 16:41 UTC, girip11 commented
> Thanks @girip11 for your (as always) excellent comments, and for holding me accountable to not writing lazy code +1
> 
> Regarding polymorphism - IMO at the moment it's not too complex that we would _need_ it, but if you wanted to submit a PR for that it would be welcome!

Sure once these PRs get merged, I would like to take a look at this config refactoring

2020-09-16 12:57 UTC, girip11 approved these changes

2020-09-16 16:33 UTC, merged