append to pythonpath instead of overwriting it
nbQA-dev/nbQA pull request #294
Opened 2020-10-05 14:41 UTC by MarcoGorelli

2020-10-05 15:56 UTC, girip11 requested changes

2020-10-05 16:26 UTC, MarcoGorelli commented on nbqa/__main__.py
> +    env["PYTHONPATH"] = env.get("PYTHONPATH", "") + os.getcwd()
thanks for explaining!

`rstrip(os.pathsep)`, I guess?

have made the update anyway, still need to figure out how to write a failing test

2020-10-05 16:38 UTC, girip11 commented on nbqa/__main__.py
> +    env["PYTHONPATH"] = env.get("PYTHONPATH", "") + os.getcwd()
> rstrip(os.pathsep), I guess?

Good catch!

2020-10-05 16:40 UTC, girip11 commented on nbqa/__main__.py
> +    env["PYTHONPATH"] = env.get("PYTHONPATH", "") + os.getcwd()
You could use the remove_comments module for testing the same. Add `remove_comments` module to `PYTHONPATH` and run the test (in addition to the fixture test case)

2020-10-06 16:40 UTC, MarcoGorelli commented on nbqa/__main__.py
> +    env["PYTHONPATH"] = env.get("PYTHONPATH", "") + os.getcwd()
Yes, that works! Thanks, is it good to go now?

2020-10-06 17:21 UTC, girip11 approved these changes

2020-10-07 07:30 UTC, merged