Add ruff tool
nbQA-dev/nbQA pull request #773
Opened 2022-11-15 11:04 UTC by marscher

I'd like an suggestion what a useful test would look like. I believe this tools output could likely change in the future, so the usefulness of strict output checking right now seems overkill.
You have to decide.

2022-11-15 11:47 UTC, marscher commented
@MarcoGorelli I think this is ready to be reviewed!

2022-11-15 12:01 UTC, MarcoGorelli requested changes
Nice work! Couple more requests:

- can we add ruff to

https://github.com/nbQA-dev/nbQA/blob/19d0e60396b7964efb21385a2a18754e45b2807e/setup.cfg#L55

?

- can we add it a `ruff` example to

https://github.com/nbQA-dev/nbQA/blob/main/docs/examples.rst

?

- let's also add a link here

https://github.com/nbQA-dev/nbQA/blob/19d0e60396b7964efb21385a2a18754e45b2807e/README.md?plain=1#L135

2022-11-15 12:14 UTC, marscher commented
Thanks for the review. I've added the requested changes.

2022-11-15 12:21 UTC, MarcoGorelli commented
Thanks! I'll try this out later but it should be good to go

2022-12-10 18:28 UTC, MarcoGorelli commented
Hey - sorry, just getting back to this now

> Also it does not fail, even if the passed notebook contains errors

hmm this doesn't look quite right - could you show an example please?

Also, looks like I need to fix compat with flake8 6.0.0 to get CI to pass, I'll do that separately

2022-12-11 14:31 UTC, MarcoGorelli commented
Can't reproduce this BTW:
```console
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/nbQA-dev$ nbqa ruff tests/data/notebook_for_testing.ipynb 
Found 7 error(s).
tests/data/notebook_for_testing.ipynb:cell_1:1:8: F401 `os` imported but unused
tests/data/notebook_for_testing.ipynb:cell_1:3:8: F401 `glob` imported but unused
tests/data/notebook_for_testing.ipynb:cell_1:5:8: F401 `nbqa` imported but unused
tests/data/notebook_for_testing.ipynb:cell_4:1:1: E402 Module level import not at top of file
tests/data/notebook_for_testing.ipynb:cell_4:1:20: F401 `random.randint` imported but unused
tests/data/notebook_for_testing.ipynb:cell_5:1:1: E402 Module level import not at top of file
tests/data/notebook_for_testing.ipynb:cell_5:2:1: E402 Module level import not at top of file
4 potentially fixable with the --fix option.
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/nbQA-dev$ echo $?
1
```

2022-12-26 14:45 UTC, MarcoGorelli commented
> I just tested the hook locally and I need to pass the "verbose" flag to pre-commit so the errors show up. Also it does not fail, even if the passed notebook contains errors. What am I missing?
>
> Ruff returns a code != 0, in case of an error.

Still can't reproduce this:
```
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ pre-commit run nbqa-ruff -a
nbqa-ruff................................................................Failed
- hook id: nbqa-ruff
- exit code: 1

notebook_for_testing.ipynb:cell_1:1:8: F401 `os` imported but unused
notebook_for_testing.ipynb:cell_1:3:8: F401 `glob` imported but unused
notebook_for_testing.ipynb:cell_1:5:8: F401 `nbqa` imported but unused
notebook_for_testing.ipynb:cell_4:1:1: E402 Module level import not at top of file
notebook_for_testing.ipynb:cell_4:1:20: F401 `random.randint` imported but unused
notebook_for_testing.ipynb:cell_5:1:1: E402 Module level import not at top of file
notebook_for_testing.ipynb:cell_5:2:1: E402 Module level import not at top of file
Found 7 error(s).
4 potentially fixable with the --fix option.
```

Let's ship it then, if any bug is reported we can address later

2022-12-26 14:45 UTC, merged

2022-12-26 14:46 UTC, MarcoGorelli commented
@all-contributors please add @marscher for features

2022-12-26 14:46 UTC, MarcoGorelli commented
@all-contributors please add @marscher for code

2022-12-28 02:13 UTC, charliermarsh commented
Apologies for the spam, but this is really cool! Thank you for the integration!

2023-01-02 14:09 UTC, MarcoGorelli commented
> Apologies for the spam, but this is really cool! Thank you for the integration!

thanks!

BTW are you signed up to github sponsors? I'd love to sponsor ruff

2023-01-02 18:37 UTC, charliermarsh commented
@MarcoGorelli - Thank you, that's super kind! I'm not signed up yet but I am considering it. I will let you know if I turn it on :)